# Default initial positions for niryo_ned2_dual_arm's ros2_control fake system

initial_positions:
  ned1_joint_1: 0
  ned1_joint_2: 0
  ned1_joint_3: 0
  ned1_joint_4: 0
  ned1_joint_5: 0
  ned1_joint_6: 0
  ned1_joint_base_to_mors_1: 0
  ned1_joint_base_to_mors_2: 0
  ned2_joint_1: 0
  ned2_joint_2: 0
  ned2_joint_3: 0
  ned2_joint_4: 0
  ned2_joint_5: 0
  ned2_joint_6: 0
  ned2_joint_base_to_mors_1: 0
  ned2_joint_base_to_mors_2: 0