# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ned1_arm_controller
    - ned1_gripper_controller
    - ned2_arm_controller
    - ned2_gripper_controller

  ned1_arm_controller:
    type: FollowJointTrajectory
    joints:
      - ned1_joint_1
      - ned1_joint_2
      - ned1_joint_3
      - ned1_joint_4
      - ned1_joint_5
      - ned1_joint_6
    action_ns: follow_joint_trajectory
    default: true
  ned1_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - ned1_joint_base_to_mors_1
      - ned1_joint_base_to_mors_2
    action_ns: follow_joint_trajectory
    default: true
  ned2_arm_controller:
    type: FollowJointTrajectory
    joints:
      - ned2_joint_1
      - ned2_joint_2
      - ned2_joint_3
      - ned2_joint_4
      - ned2_joint_5
      - ned2_joint_6
    action_ns: follow_joint_trajectory
    default: true
  ned2_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - ned2_joint_base_to_mors_1
      - ned2_joint_base_to_mors_2
    action_ns: follow_joint_trajectory
    default: true
