# Default initial positions for niryo_ned2_gripper1_n_camera's ros2_control fake system

initial_positions:
  joint_1: 0
  joint_2: 0
  joint_3: 0
  joint_4: 0
  joint_5: 0
  joint_6: 0
  joint_base_to_mors_1: 0
  joint_base_to_mors_2: 0